version: "3.9"

services:
  web:
    build: .
    command: bundle exec rerun --dir app,config -- rackup -o 0.0.0.0 -p 4567 config.ru
    tty: true
    ports:
      - "4567:4567"
    environment:
      RACK_ENV: development
      OPENSEARCH_URL: http://opensearch:9200
    volumes:
      - .:/app
    depends_on: []
